### ISSUE TITLE
Bug: parsimonious.exceptions.ParseError: Rule 'q_clause'

### ISSUE THREAD

**Issue by montenegrodr** [slavak/PyNotam#1]
Thanks for the excellent work. But I am facing a problem with the following:

```
>>> s = """(A3321/16 NOTAMN
... Q) EGTT/QOBCE/IV/M  /AE/000/002/5129N00026W001
... A) EGLL B) 1610010800 C) 1612311800
... E) 
... CRANE OPR PSN 512850.02N 0002620.96W (LONGFORD) , MAX HEIGHT 81FT AGL
... /160FT AMSL)"""
>>> n  = notam.Notam.from_str(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robson/dev/workspaces/tools/notam_crawler/notam_crawler/PyNotam/notam.py", line 79, in from_str
    visitor.parse(s)
  File "/home/robson/.pyenv/versions/3.5.2_notam/lib/python3.5/site-packages/parsimonious/nodes.py", line 247, in parse
    return self._parse_or_match(text, pos, 'parse')
  File "/home/robson/.pyenv/versions/3.5.2_notam/lib/python3.5/site-packages/parsimonious/nodes.py", line 282, in _parse_or_match
    return self.visit(getattr(self.grammar, method_name)(text, pos=pos))
  File "/home/robson/.pyenv/versions/3.5.2_notam/lib/python3.5/site-packages/parsimonious/grammar.py", line 123, in parse
    return self.default_rule.parse(text, pos=pos)
  File "/home/robson/.pyenv/versions/3.5.2_notam/lib/python3.5/site-packages/parsimonious/expressions.py", line 110, in parse
    node = self.match(text, pos=pos)
  File "/home/robson/.pyenv/versions/3.5.2_notam/lib/python3.5/site-packages/parsimonious/expressions.py", line 127, in match
    raise error
parsimonious.exceptions.ParseError: Rule 'q_clause' didn't match at 'Q) EGTT/QOBCE/IV/M  ' (line 2, column 1).
```

**Comment by slavak** [comment]
Thanks for the bug report!

The error is caused by two unexpected spaces in the "Purpose" field of the "Qualifiers" line:

```
Q) EGTT/QOBCE/IV/M  /AE/000/002/5129N00026W001
                  ^^
```

At the moment the parsing grammar is defined to consider this format invalid. I will look into this aspect of the NOTAM format as officially defined to see whether this should be considered a valid NOTAM. Even if not, I'll need to think about the possibility of supporting this.

If you have any input on the above points please chime in. Also, do you mind if I ask for the source of this NOTAM?

In the meantime, manually (or programmatically) trimming those unexpected spaces will fix the issue:
```
>>> s = """(A3321/16 NOTAMN
Q) EGTT/QOBCE/IV/M/AE/000/002/5129N00026W001
A) EGLL B) 1610010800 C) 1612311800
E) 
CRANE OPR PSN 512850.02N 0002620.96W (LONGFORD) , MAX HEIGHT 81FT AGL
/160FT AMSL)"""
>>> n = notam.Notam.from_str(s)
>>> n.fir_long
'London FIR (civil)'
```

_I believe the `fir_long` method I used for the demonstration above doesn't exist in the pushed code yet. Sorry about that._

**Comment by slavak** [comment]
As far as I can see this is not a valid format as defined. Barring more details about the source of this specific NOTAM or another reason to believe there are more than a few NOTAMs out in the wild formatted in this way, I don't see a reason to add support for this behavior at this time.

montenegrodr, if you have further information please feel free to comment and/or reopen the issue.
